download:
  domain:
    amass:
      toolname: amass
      whetherdownload: True
      link: https://github.com/OWASP/Amass/releases/download/v3.21.2/amass_linux_amd64.zip
      downloadfile: amass.zip
#      unzipsubfile: amass_windows_amd64
      source_name: amass_linux_amd64/
      final_name: amass/
      tool_main_filename: amass
      topath:
        - core/tools/domain/
        - /
#        - core/tools/domain/amass/
#        - amass/
    ksubdomain:
      toolname: ksubdomain
      whetherdownload: True
      link: https://github.com/boy-hack/ksubdomain/releases/download/v1.9.5/KSubdomain-v1.9.5-linux.tar
      downloadfile: ksubdomain.tar
      source_name: ksubdomain
      final_name: ksubdomain
      tool_main_filename: ksubdomain
      topath:
        - core/tools/domain/ksubdomain/
        - ksubdomain/
    subfinder:
      toolname: subfinder
      whetherdownload: True
      link: https://github.com/projectdiscovery/subfinder/releases/download/v2.5.5/subfinder_2.5.5_linux_amd64.zip
      downloadfile: subfinder.zip
      source_name: subfinder
      final_name: subfinder
      tool_main_filename: subfinder
      topath:
        - core/tools/domain/subfinder/
        - subfinder/
    oneforall:
      toolname: oneforall
      whetherdownload: False
      link:
      downloadfile:
      source_name:
      final_name:
      tool_main_filename: oneforall.py
      topath:
        - core/tools/domain/OneForAll/
        - OneForAll/
    ip2location:
      toolname: ip2location
      whetherdownload: True
      link: https://github.com/shmilylty/OneForAll/blob/master/data/ip2location.zip?raw=true
      downloadfile: ip2location.zip
      source_name: ip2location.db
      final_name: ip2location.db
      tool_main_filename: ip2location.db
      topath:
        - core/tools/domain/OneForAll/data/
        - OneForAll/data/
    subnames_big:
      # https://raw.githubusercontent.com/shmilylty/OneForAll/blob/master/data/subnames_big.7z
      toolname: subnames_big
      whetherdownload: True
      link: https://github.com/shmilylty/OneForAll/blob/master/data/subnames_big.7z?raw=true
      downloadfile: subnames_big.7z
      source_name: subnames_big.7z
      final_name: subnames_big.7z
      tool_main_filename: subnames_big.7z
      topath:
        - core/tools/domain/OneForAll/data/
        - OneForAll/data/
    ip2region:
      toolname: ip2region
      whetherdownload: True
      link: https://github.com/shmilylty/OneForAll/blob/master/data/ip2region.db?raw=true
      downloadfile: ip2region.db
      source_name: ip2region.db
      final_name: ip2region.db
      tool_main_filename: ip2region.db
      topath:
        - core/tools/domain/OneForAll/data/
        - OneForAll/data/
  finger:
    ehole:
      toolname: ehole
      whetherdownload: False
      link:
      downloadfile:
      source_name:
      final_name:
      tool_main_filename:
      topath:
        - core/tools/finger/Ehole/
        - Ehole/
    httpx:
      toolname: httpx
      whetherdownload: True
      link: https://github.com/projectdiscovery/httpx/releases/download/v1.2.4/httpx_1.2.4_linux_amd64.zip
      downloadfile: httpx.zip
      source_name: httpx
      final_name: httpx
      tool_main_filename: httpx
      topath:
        - core/tools/finger/httpx/
        - httpx/
    webanalyze:
      toolname: webanalyze
      whetherdownload: True
      link: https://github.com/rverton/webanalyze/releases/download/v0.3.8/webanalyze_0.3.8_Linux_x86_64.tar.gz
      downloadfile: webanalyze.tar.gz
      source_name: webanalyze
      final_name: webanalyze
      tool_main_filename: webanalyze
      topath:
        - core/tools/finger/webanalyze/
        - webanalyze/
  portscan:
    TxPortMap:
      toolname: TxPortMap
      whetherdownload: True
      link: https://github.com/4dogs-cn/TXPortMap/releases/download/v1.1.2/TxPortMap_linux_x64
      downloadfile: TxPortMap
      source_name: TxPortMap
      final_name: TxPortMap
      tool_main_filename: TxPortMap
      topath:
        - core/tools/portscan/TxPortMap/
        - TxPortMap/
    # 暂不使用
    dismap:
      toolname: dismap
      whetherdownload: False
      link:
      downloadfile:
      source_name:
      final_name:
      tool_main_filename:
      topath:
        - core/tools/portscan/dismap/
        - dismap/
    naabu:
      toolname: naabu
      whetherdownload: True
      link: https://github.com/projectdiscovery/naabu/releases/download/v2.1.1/naabu_2.1.1_linux_amd64.zip
      downloadfile: naabu.zip
      source_name: naabu
      final_name: naabu
      tool_main_filename: naabu
      topath:
        - core/tools/portscan/naabu/
        - naabu/
  sensitiveinfo:
    chrome-linux:
      toolname: chrome-linux
      whetherdownload: True
      link: https://commondatastorage.googleapis.com/chromium-browser-snapshots/Linux_x64/1086242/chrome-linux.zip
      downloadfile: chrome-linux.zip
      source_name: chrome-linux/
      final_name: chrome-linux/
      tool_main_filename: chrome
      topath:
        - core/tools/sensitiveinfo/
        - /
    crawlergo:
      toolname: crawlergo
      whetherdownload: True
      link: https://github.com/Qianlitp/crawlergo/releases/download/v0.4.4/crawlergo_linux_amd64
      downloadfile: crawlergo
      source_name: crawlergo
      final_name: crawlergo
      tool_main_filename: crawlergo
      topath:
        - core/tools/sensitiveinfo/crawlergo/
        - crawlergo/
    rad:
      toolname: rad
      whetherdownload: True
      link: https://github.com/chaitin/rad/releases/download/0.4/rad_linux_amd64.zip
      downloadfile: rad.zip
      source_name: rad_linux_amd64
      final_name: rad
      tool_main_filename: rad
      topath:
        - core/tools/sensitiveinfo/rad/
        - rad/
    emailall:
      # https://github.com/Taonn/EmailAll/archive/refs/heads/master.zip 修改过
      toolname: emailall
      whetherdownload: False
      link:
      downloadfile: emailall.zip
      source_name:
      final_name:
      tool_main_filename: emailall.py
      topath:
        - core/tools/sensitiveinfo/emailall/
        - emailall/
    gospider:
      toolname: gospider
      whetherdownload: True
      link: https://github.com/jaeles-project/gospider/releases/download/v1.1.6/gospider_v1.1.6_linux_x86_64.zip
      downloadfile: gospider.zip
      source_name: gospider_v1.1.6_linux_x86_64/
      final_name: gospider/
      tool_main_filename: gospider
      topath:
        - core/tools/sensitiveinfo/
        - /
#        - core/tools/sensitiveinfo/gospider/
#        - gospider/
    hakrawler:
      # 修改了加了-f参数
      toolname: hakrawler
      whetherdownload: True
      link: https://github.com/komomon/hakrawler_plus/blob/main/hakrawler?raw=true
      downloadfile: hakrawler
      source_name: hakrawler
      final_name: hakrawler
      tool_main_filename: hakrawler
      topath:
        - core/tools/sensitiveinfo/hakrawler/
        - hakrawler/
    dirsearch:
      # zanbuyong，不移动 dirsearch-master/ /
      toolname: dirsearch
      whetherdownload: False
      link: https://github.com/maurosoria/dirsearch/archive/refs/heads/master.zip
      downloadfile: dirsearch.zip
      source_name:
      final_name:
      tool_main_filename: dirsearch.py
      topath:
        - core/tools/sensitiveinfo/dirsearch/
        - dirsearch/
    gau:
      toolname: gau
      whetherdownload: True
      link: https://github.com/lc/gau/releases/download/v2.1.2/gau_2.1.2_linux_amd64.tar.gz
      downloadfile: gau.tar.gz
      source_name: gau
      final_name: gau
      tool_main_filename: gau
      topath:
        - core/tools/sensitiveinfo/gau/
        - gau/
    urlcollector:
      toolname: urlcollector
      whetherdownload: False
      link:
      downloadfile:
      source_name:
      final_name:
      tool_main_filename:
      topath:
        - core/tools/sensitiveinfo/urlcollector/
        - urlcollector/
    URLFinder:
      toolname: URLFinder
      whetherdownload: True
      link: https://github.com/pingc0y/URLFinder/blob/master/URLFinder-linux-amd64?raw=true
      downloadfile: URLFinder
      source_name: URLFinder
      final_name: URLFinder
      tool_main_filename: URLFinder
      topath:
        - core/tools/sensitiveinfo/URLFinder/
        - URLFinder/
  vulscan:
    afrog:
      toolname: afrog
      whetherdownload: True
      link: https://github.com/zan8in/afrog/releases/download/v2.1.1/afrog_2.1.1_linux_amd64.zip
      downloadfile: afrog.zip
      source_name: afrog
      final_name: afrog
      tool_main_filename: afrog
      topath:
        - core/tools/vulscan/afrog/
        - afrog/
    goon:
      toolname: goon
      whetherdownload: True
      link: https://github.com/i11us0ry/goon/releases/download/v3.5/goon3_lin_amd64.zip
      downloadfile: goon.zip
      source_name: goon3_lin_amd64
      final_name: goon
      tool_main_filename: goon
      topath:
        - core/tools/vulscan/goon/
        - goon/
    nuclei:
      toolname: nuclei
      whetherdownload: True
      link: https://github.com/projectdiscovery/nuclei/releases/download/v2.8.3/nuclei_2.8.3_linux_amd64.zip
      downloadfile: nuclei.zip
      source_name: nuclei
      final_name: nuclei
      tool_main_filename: nuclei
      topath:
        - core/tools/vulscan/nuclei/
        - nuclei/
    SweetBabyScan:
      toolname: SweetBabyScan
      whetherdownload: True
      link: https://github.com/inbug-team/SweetBabyScan/releases/download/v0.1.0/SbScanLinuxAmd64
      downloadfile: SweetBabyScan
      #      source_name: SbScanAmd64.exe
      source_name: SweetBabyScan
      final_name: SweetBabyScan
      tool_main_filename: SweetBabyScan
      topath:
        - core/tools/vulscan/SweetBabyScan/
        - SweetBabyScan/

    vulmap:
      # py
      toolname: vulmap
      whetherdownload: True
      link: https://github.com/zhzyker/vulmap/archive/refs/tags/v0.9.zip
      downloadfile: vulmap.zip
      source_name: vulmap-0.9/
      final_name: vulmap/
      tool_main_filename: vulmap.py
      topath:
        - core/tools/vulscan/
        - /
#        - core/tools/vulscan/vulmap/
#        - vulmap/
    vscan:
      toolname: vscan
      whetherdownload: True
      link: https://github.com/veo/vscan/releases/download/v2.1.0/vscan_2.1.0_linux_amd64.zip
      downloadfile: vscan.zip
      source_name: vscan
      final_name: vscan
      tool_main_filename: vscan
      topath:
        - core/tools/vulscan/vscan/
        - vscan/



































